/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { RideService } from "../ride.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { RideCreateInput } from "./RideCreateInput";
import { Ride } from "./Ride";
import { RideFindManyArgs } from "./RideFindManyArgs";
import { RideWhereUniqueInput } from "./RideWhereUniqueInput";
import { RideUpdateInput } from "./RideUpdateInput";
import { RiderBookingFindManyArgs } from "../../riderBooking/base/RiderBookingFindManyArgs";
import { RiderBooking } from "../../riderBooking/base/RiderBooking";
import { RiderBookingWhereUniqueInput } from "../../riderBooking/base/RiderBookingWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class RideControllerBase {
  constructor(
    protected readonly service: RideService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Ride })
  @nestAccessControl.UseRoles({
    resource: "Ride",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createRide(@common.Body() data: RideCreateInput): Promise<Ride> {
    return await this.service.createRide({
      data: data,
      select: {
        createdAt: true,
        destination: true,
        driver: true,
        id: true,
        location: true,
        passengers: true,
        price: true,
        status: true,
        time: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Ride] })
  @ApiNestedQuery(RideFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Ride",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async rides(@common.Req() request: Request): Promise<Ride[]> {
    const args = plainToClass(RideFindManyArgs, request.query);
    return this.service.rides({
      ...args,
      select: {
        createdAt: true,
        destination: true,
        driver: true,
        id: true,
        location: true,
        passengers: true,
        price: true,
        status: true,
        time: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Ride })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Ride",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async ride(
    @common.Param() params: RideWhereUniqueInput
  ): Promise<Ride | null> {
    const result = await this.service.ride({
      where: params,
      select: {
        createdAt: true,
        destination: true,
        driver: true,
        id: true,
        location: true,
        passengers: true,
        price: true,
        status: true,
        time: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Ride })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Ride",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateRide(
    @common.Param() params: RideWhereUniqueInput,
    @common.Body() data: RideUpdateInput
  ): Promise<Ride | null> {
    try {
      return await this.service.updateRide({
        where: params,
        data: data,
        select: {
          createdAt: true,
          destination: true,
          driver: true,
          id: true,
          location: true,
          passengers: true,
          price: true,
          status: true,
          time: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Ride })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Ride",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteRide(
    @common.Param() params: RideWhereUniqueInput
  ): Promise<Ride | null> {
    try {
      return await this.service.deleteRide({
        where: params,
        select: {
          createdAt: true,
          destination: true,
          driver: true,
          id: true,
          location: true,
          passengers: true,
          price: true,
          status: true,
          time: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/riderBookings")
  @ApiNestedQuery(RiderBookingFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "RiderBooking",
    action: "read",
    possession: "any",
  })
  async findRiderBookings(
    @common.Req() request: Request,
    @common.Param() params: RideWhereUniqueInput
  ): Promise<RiderBooking[]> {
    const query = plainToClass(RiderBookingFindManyArgs, request.query);
    const results = await this.service.findRiderBookings(params.id, {
      ...query,
      select: {
        bookingTime: true,
        createdAt: true,
        id: true,
        paymentMethod: true,

        ride: {
          select: {
            id: true,
          },
        },

        rider: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/riderBookings")
  @nestAccessControl.UseRoles({
    resource: "Ride",
    action: "update",
    possession: "any",
  })
  async connectRiderBookings(
    @common.Param() params: RideWhereUniqueInput,
    @common.Body() body: RiderBookingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      riderBookings: {
        connect: body,
      },
    };
    await this.service.updateRide({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/riderBookings")
  @nestAccessControl.UseRoles({
    resource: "Ride",
    action: "update",
    possession: "any",
  })
  async updateRiderBookings(
    @common.Param() params: RideWhereUniqueInput,
    @common.Body() body: RiderBookingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      riderBookings: {
        set: body,
      },
    };
    await this.service.updateRide({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/riderBookings")
  @nestAccessControl.UseRoles({
    resource: "Ride",
    action: "update",
    possession: "any",
  })
  async disconnectRiderBookings(
    @common.Param() params: RideWhereUniqueInput,
    @common.Body() body: RiderBookingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      riderBookings: {
        disconnect: body,
      },
    };
    await this.service.updateRide({
      where: params,
      data,
      select: { id: true },
    });
  }
}
