/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { RiderBookingService } from "../riderBooking.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { RiderBookingCreateInput } from "./RiderBookingCreateInput";
import { RiderBooking } from "./RiderBooking";
import { RiderBookingFindManyArgs } from "./RiderBookingFindManyArgs";
import { RiderBookingWhereUniqueInput } from "./RiderBookingWhereUniqueInput";
import { RiderBookingUpdateInput } from "./RiderBookingUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class RiderBookingControllerBase {
  constructor(
    protected readonly service: RiderBookingService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: RiderBooking })
  @nestAccessControl.UseRoles({
    resource: "RiderBooking",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createRiderBooking(
    @common.Body() data: RiderBookingCreateInput
  ): Promise<RiderBooking> {
    return await this.service.createRiderBooking({
      data: {
        ...data,

        ride: data.ride
          ? {
              connect: data.ride,
            }
          : undefined,
      },
      select: {
        bookingTime: true,
        createdAt: true,
        id: true,
        paymentMethod: true,

        ride: {
          select: {
            id: true,
          },
        },

        rider: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [RiderBooking] })
  @ApiNestedQuery(RiderBookingFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "RiderBooking",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async riderBookings(@common.Req() request: Request): Promise<RiderBooking[]> {
    const args = plainToClass(RiderBookingFindManyArgs, request.query);
    return this.service.riderBookings({
      ...args,
      select: {
        bookingTime: true,
        createdAt: true,
        id: true,
        paymentMethod: true,

        ride: {
          select: {
            id: true,
          },
        },

        rider: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: RiderBooking })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "RiderBooking",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async riderBooking(
    @common.Param() params: RiderBookingWhereUniqueInput
  ): Promise<RiderBooking | null> {
    const result = await this.service.riderBooking({
      where: params,
      select: {
        bookingTime: true,
        createdAt: true,
        id: true,
        paymentMethod: true,

        ride: {
          select: {
            id: true,
          },
        },

        rider: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: RiderBooking })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "RiderBooking",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateRiderBooking(
    @common.Param() params: RiderBookingWhereUniqueInput,
    @common.Body() data: RiderBookingUpdateInput
  ): Promise<RiderBooking | null> {
    try {
      return await this.service.updateRiderBooking({
        where: params,
        data: {
          ...data,

          ride: data.ride
            ? {
                connect: data.ride,
              }
            : undefined,
        },
        select: {
          bookingTime: true,
          createdAt: true,
          id: true,
          paymentMethod: true,

          ride: {
            select: {
              id: true,
            },
          },

          rider: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: RiderBooking })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "RiderBooking",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteRiderBooking(
    @common.Param() params: RiderBookingWhereUniqueInput
  ): Promise<RiderBooking | null> {
    try {
      return await this.service.deleteRiderBooking({
        where: params,
        select: {
          bookingTime: true,
          createdAt: true,
          id: true,
          paymentMethod: true,

          ride: {
            select: {
              id: true,
            },
          },

          rider: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
